1. In this lesson, you created a middleware function called asyncWrapper. Why?
The asyncWrapper is a function created to wrap the any controller and provide the method with async functionality as well as try/catch functionality. Without the wrapper each controller would have to have async/await and a try/catch block added to the code.


2. Suppose that you want to make sure that both a status code and and error message are send back to the user when they request the URL for a task that does not exist. Assume that youâ€™ve created a CustomAPIError class and an error handler that references that class. Complete the code:
const getTask = asyncWrapper(async (req, res, next) => {
  const { id: taskID } = req.params;
  const task = await Task.findOne({ _id: taskID });
  if (!task) {
    return next(createCustomError(`No task with the id: ${taskID}`, 404))
  }
  res.status(200).json({ task });
});